language: cpp
compiler:
    - clang
    - gcc
dist: xenial
addons:
    apt:
        packages:
            - python3
            - python3-pip
            - python3-setuptools

before_install:
    - pip3 install -U setuptools
    - pip3 install -U online-judge-tools=='7.*'
script:
    - bash test.sh
